### PR TITLE
Adjust skills and tools names

### PR DESCRIPTION
**Pull request by dSupertramp**
Hi Luke! Danilo here!
I really love your dashboard, and I decided to create a dictionary that maps the names of programming languages ​​and tools to the actually correct names, so you have a cleaner view - I'll probably miss some more, but I'll add them in the future.

Have a nice day!

### CODE REVIEW

**Comment by dSupertramp** [comment]
I should take a look: currently the best solution would be to leave the list `keywords_programming`, and I'll see how to fix it later

**Comment by lukebarousse** [comment]
Yeah, my recommendation would be to create a dictionary for `keywords_programming` and then a dictionary for all the other keywords `keywords_skills`.  From there, you can create a dictionary with both by adding them together (I.e., `keywords_all`) and then when it comes to the programming filter, you just use that `keywords_programming` dictionary.  The process basically ensures DRY.

**Comment by dSupertramp** [comment]
I splitted the big keywords into two different dicts, and now it's working!

**Comment by lukebarousse** [comment]
Hey Danilo! Thanks for these quick changes! I merged them.

On a related note, I should have told you before, but here is a list of all the keywords:
```
keywords_programming = [
'sql', 'python', 'r', 'c', 'c#', 'javascript', 'js',  'java', 'scala', 'sas', 'matlab', 
'c++', 'c/c++', 'perl', 'go', 'typescript', 'bash', 'html', 'css', 'php', 'powershell', 'rust', 
'kotlin', 'ruby',  'dart', 'assembly', 'swift', 'vba', 'lua', 'groovy', 'delphi', 'objective-c', 
'haskell', 'elixir', 'julia', 'clojure', 'solidity', 'lisp', 'f#', 'fortran', 'erlang', 'apl', 
'cobol', 'ocaml', 'crystal', 'javascript/typescript', 'golang', 'nosql', 'mongodb', 't-sql', 'no-sql',
'visual_basic', 'pascal', 'mongo', 'pl/sql',  'sass', 'vb.net', 'mssql', 
]

keywords_libraries = [
'scikit-learn', 'jupyter', 'theano', 'openCV', 'spark', 'nltk', 'mlpack', 'chainer', 'fann', 'shogun', 
'dlib', 'mxnet', 'node.js', 'vue', 'vue.js', 'keras', 'ember.js', 'jse/jee',
]

keywords_analyst_tools = [
'excel', 'tableau',  'word', 'powerpoint', 'looker', 'powerbi', 'outlook', 'azure', 'jira', 'twilio',  'snowflake', 
'shell', 'linux', 'sas', 'sharepoint', 'mysql', 'visio', 'git', 'mssql', 'powerpoints', 'postgresql', 'spreadsheets',
'seaborn', 'pandas', 'gdpr', 'spreadsheet', 'alteryx', 'github', 'postgres', 'ssis', 'numpy', 'power_bi', 'spss', 'ssrs', 
'microstrategy',  'cognos', 'dax', 'matplotlib', 'dplyr', 'tidyr', 'ggplot2', 'plotly', 'esquisse', 'rshiny', 'mlr',
'docker', 'linux', 'jira',  'hadoop', 'airflow', 'redis', 'graphql', 'sap', 'tensorflow', 'node', 'asp.net', 'unix',
'jquery', 'pyspark', 'pytorch', 'gitlab', 'selenium', 'splunk', 'bitbucket', 'qlik', 'terminal', 'atlassian', 'unix/linux',
'linux/unix', 'ubuntu', 'nuix', 'datarobot',
]

keywords_cloud_tools = [
'aws', 'azure', 'gcp', 'snowflake', 'redshift', 'bigquery', 'aurora',
]
```
It's on my [kaggle notebook](https://www.kaggle.com/code/lukebarousse/data-analyst-skill-analysis)

**Comment by lukebarousse** [comment]
Hey @dSupertramp, I just invited you to the repo for [datanerd.tech](https://datanerd.tech).  This is the updated app and one I'd like to develop further as this one focuses on jobs beyond just Data Analysts in the US.

**Comment by dSupertramp** [comment]
That's fantastic @lukebarousse thank you!
I'll adjust these lists too!

**Pull request merged**
