### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Matteo-Botta**
I'm not a native speaker, but I guess you meant "what's up' here.

### CODE REVIEW

**Review by lukebarousse — APPROVED** [review]
Ha, well TBH that's how I say it, but that's more of a slang use.  Let's update it to make it more clear.  Thanks for this.

**Comment by Matteo-Botta** [comment]
Hi Luke!

TBH I’m learning the ropes with GitHub and wanted to check out how collaboration and  "pulling request” function works.

On a different topic, If I understand well, the roadmap you recommend to learn how to web scraping is:
-Python for everybody (Coursera)
-Web scraping in Python (Datacamp)

Or is there anything else?

BTW, I’m big fun of your work on YouTube.

Best regards,
Matteo Botta

**Comment by lukebarousse** [comment]
Yeah, this is a great way to find out how to a PR; so def hoped you learn something!

Yeah for webscraping I think that's a good approach.  Depending on your coding proficiency you may be able skip the datacamp stuff and just learn on your own that portion. 

Glad you are enjoying the content!

**Comment by Matteo-Botta** [comment]
At the beginning of my coding journey, for now.
Thanks for sharing your opinion.


Best regards,
Matteo Botta

**Pull request merged**
