### PR TITLE
Created CurrencyConverter.py

### PR DESCRIPTION
**Pull request by asadali27232**
Adding a new Feature: Convert the salary columns amount to the selected country from the filter in the graph.

### CODE REVIEW

**Comment by lukebarousse** [comment]
Hey, love this addition, but for this app I only have United States data and there is no country selection filter. Are you trying to add this to [datanerd.tech](https://datanerd.tech)?

**Comment by asadali27232** [comment]
> Hey, love this addition, but for this app, I only have United States data and there is no country selection filter. Are you trying to add this to [datanerd.tech](https://datanerd.tech)?

image

Yes trying to add this feature on the salary page at [https://datanerd.tech/Salary](https://datanerd.tech/Salary). I wanted to contribute to this app but the [About Section](https://datanerd.tech/About) of this app redirected to this repo.

I have searched a lot where the working code for the Country filter in this repo but I was unable to find out, then I realized that this is not the repo for [datanerd.tech](https://datanerd.tech) [About Section](https://datanerd.tech/About) redirected me to some other projects's repo.

But still, I wanted this feature in [datanerd.tech](https://datanerd.tech) so I pushed the change here.

**Comment by lukebarousse** [comment]
Alright, let me add you to the datanerd.tech repo.  It's a private repo, so that's why it's not on the About Me page... I need to update the about me page to give more precise instructions on how those can get access to the private repo. 

Also, I will close this PR so we can merge there instead.

**Comment by asadali27232** [comment]
> Alright, let me add you to the datanerd.tech repo. It's a private repo, so that's why it's not on the About Me page... I need to update the about me page to give more precise instructions on how those can get access to the private repo.
> 
> Also, I will close this PR so we can merge there instead.

Sure! will happy to work there

**Pull request closed without merging**
